version: "3.9"

services:
  # Application
  app:
    build:
      context: .
      dockerfile: _docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - "database"
    networks:
      - web
    container_name: app
    restart: always
  # Web Server
  server:
    image: nginx:alpine
    build:
      context: .
      dockerfile: _docker/web.dockerfile
    working_dir: /var/www
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./_docker/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - "app"
    container_name: server
    restart: always
    networks:
      - web
  # Database
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    container_name: db
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - web
  # Redis
  redis:
    image: redis:4.0
    container_name: redis
    ports:
      - "6382:6379"
    networks:
      - web
    restart: always
  # Pgadmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - web

networks:
  web:
    external: true

volumes:
  dbdata:
  pgadmin-data:
